### ISSUE TITLE
Consistent naming conventions throughout interfaces

### ISSUE THREAD

**Issue by balupton** [textileio/meta#34] opened 2019-05-23 07:48 UTC
Currently in `textile-go` there isn't much consistency with the naming convention for methods.

# Decided

- `Ipfs` over `IPFS`, `Ipfs` is what IPFS uses inside their packages
- `ID` over `Id`, consistent with larger go ecosystem
- `URL` over `Url`, consistent with larger go ecosystem

# Discussions

## go-textile

Currently:

- CLI uses `cmd.{Noun}{Verb}` for commands, and `{verb}{Noun}` for helpers
  - This made autocomplete for typing all the commands easier, as `{Noun}*` groups everything to the current noun.
- HTTP API methods uses `a.{verb}{Noun}` for both responders and helpers.
  - Causes `get` to autocomplete to getting everything, rather than just a specific noun
- Models seems to have no convention

Proposition:

- Have the HTTP API follow the CLI in naming convention
- For models, I'm unsure what makes sense

**Comment by sanderpick** [comment] 2019-05-23 10:20
The problem is just that the proto models spit out TitleCase for abbreviations like Ipfs and Id. This is a known issue that go-ipfs fights as well. I’ve adopted it elsewhere since we expose those models to users (go-ipfs doesn’t).

The models have a convention. It’s lowercase everywhere, with underscores for multi word names so that the resulting JSON is snake case. There may be a camelCase usage in the older messages models, but we could update with everything else without breaking.

**Comment by carsonfarmer** [comment] 2019-10-22 17:13
Closing this in favor of specific issues on offending projects and repos.

**Closed by carsonfarmer** 2019-10-22 17:13 UTC
Labels: 1 - proposed, affects docs, affects ecosystem, affects tooling, type discussion, type task
